### ISSUE TITLE
The purpose and format of `values-global.yaml` is not documented

### ISSUE THREAD

**Issue by adelton** [validatedpatterns/docs#340]
Reading https://validatedpatterns.io/patterns/multicloud-gitops/mcg-getting-started/, there are steps like

> `vi values-global.yaml`
>
> `git add values-global.yaml`
>
> `git commit values-global.yaml`

there.  Content of that file is in turn

```
---
global:
  pattern: multicloud-gitops

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

main:
  clusterGroupName: hub

  multiSourceConfig:
    enabled: true
```

However, it is not clear what CSV that `useCSV` is about, what syncing and installation that `syncPolicy` and `installPlanApproval`, or what the `clusterGroupName` value is for and what happens if any of those values get changed.

If there is something that the user following the https://validatedpatterns.io/patterns/multicloud-gitops/mcg-getting-started/ guidance should look for and change, it should be clearly documented.

If the file should be left as it is because for this pattern no changes are needed, that `vi values-global.yaml` step likely should not be there at all.
